version: '3'
services: 
  skywalking-es:
    container_name: skywalking-es
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=skywalking"
      - "cluster.name=skywalking-cluster"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    
    
