# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM maven:3.5.3-jdk-8 as builder

LABEL maintainer="HanSenJ <28707699@qq.com>"

ARG TZ="UTC"
ARG BUILD_USER="apache"

ENV TZ ${TZ}
ENV REPO_ADDR https://github.com/${BUILD_USER}/incubator-skywalking.git

RUN apt-get upgrade -y \
    && apt-get install tzdata git -y \
    && git clone ${REPO_ADDR} /skywalking \
    && (cd /skywalking \
    && git submodule init \
    && git submodule update \
    && mvn clean package -DskipTests) \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && apt-get clean

FROM openjdk:8u151-jdk

ARG TZ="UTC"
ARG TEST_DATABASE="es"

ENV TZ ${TZ}
ENV TEST_DATABASE ${TEST_DATABASE}
ENV SKYWALKING_HOME /usr/lib/skywalking

COPY --from=builder /skywalking/dist/*.tar.gz /

RUN apt-get upgrade -y \
    && apt-get install tzdata -y \
    && mkdir ${SKYWALKING_HOME} \
	&& tar -zxf /*.tar.gz -C ${SKYWALKING_HOME} --strip-components 1 \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && apt-get clean \
    && rm -rf /*.tar.gz

COPY bin/*.sh ${SKYWALKING_HOME}/bin/

WORKDIR ${SKYWALKING_HOME}/bin

CMD ["/bin/bash"]
